server:
  port: 8081

#datasource specific properties
spring:
  datasource:
    username: root
    password: abcd
    url: jdbc:mysql://localhost:3306/ecomdb
#jpa properties

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true